name: React App build workflow
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./dist

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with: 
        server: ftp.proexweb.com
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
        server-dir: /public_html/production/