name: Sync FTP
on:
  push:
    branches:
      - gh-pages
jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with: 
        server: ftp.proexweb.com
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
        server-dir: /production/